services:

  worker:
    image: "${ECR_REPO_BASE_URL}/upwork-rag-worker-${APP_ENV}:${APP_RELEASE:-latest}"
    container_name: worker
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "5678:5678"
    volumes:
      - ./src:/app/src:rw
    command: serve